services:
  akk:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: akk
    environment:
      - DB_HOST=akk-psql
      - REDIS_HOST=akk-redis
    depends_on:
      - akk-psql
      - akk-redis
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:8002:8002"
    restart: always

  akk-psql:
    image: postgres:17-alpine
    container_name: akk-psql
    environment:
      - POSTGRES_USER=nolik
      - POSTGRES_PASSWORD=Nslsom!
      - POSTGRES_DB=akk
    volumes:
      - akk_psql_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    restart: always

  akk-redis:
    image: redis:8-alpine
    container_name: akk-redis
    ports:
      - "127.0.0.1:6379:6379"
    restart: always

volumes:
  akk_psql_data:

networks:
  default:
    name: akk-network
